# SkillForge AI - Comprehensive Security Policy
# This file defines the security policies and controls for the SkillForge AI platform

apiVersion: v1
kind: ConfigMap
metadata:
  name: skillforge-ai-security-policy
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: skillforge-ai
    app.kubernetes.io/component: security
data:
  security-policy.yaml: |
    # SkillForge AI Security Policy
    version: "1.0.0"
    last_updated: "2024-01-15"
    
    # Data Classification
    data_classification:
      public:
        - marketing_content
        - public_job_postings
        - general_skill_information
      internal:
        - system_logs
        - performance_metrics
        - aggregated_analytics
      confidential:
        - user_profiles
        - assessment_results
        - learning_progress
        - job_applications
      restricted:
        - authentication_credentials
        - payment_information
        - personal_identifiers
        - private_communications
    
    # Encryption Requirements
    encryption:
      at_rest:
        algorithm: "AES-256-GCM"
        key_management: "AWS KMS"
        databases: "required"
        file_storage: "required"
        backups: "required"
      in_transit:
        protocol: "TLS 1.3"
        minimum_version: "TLS 1.2"
        cipher_suites:
          - "TLS_AES_256_GCM_SHA384"
          - "TLS_CHACHA20_POLY1305_SHA256"
          - "TLS_AES_128_GCM_SHA256"
        certificate_validation: "required"
        hsts_enabled: true
        hsts_max_age: 31536000
    
    # Authentication & Authorization
    authentication:
      password_policy:
        min_length: 12
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_special_chars: true
        max_age_days: 90
        history_count: 12
        lockout_attempts: 5
        lockout_duration: 900  # 15 minutes
      hashing:
        algorithm: "Argon2id"
        memory_cost: 65536  # 64 MB
        time_cost: 3
        parallelism: 4
        salt_length: 32
      mfa:
        required_for: ["admin", "privileged_users"]
        methods: ["totp", "sms", "email"]
        backup_codes: 10
        session_timeout: 3600  # 1 hour
      session_management:
        secure_cookies: true
        httponly_cookies: true
        samesite: "Strict"
        session_timeout: 28800  # 8 hours
        idle_timeout: 3600  # 1 hour
        concurrent_sessions: 3
    
    # API Security
    api_security:
      rate_limiting:
        default: "100/minute"
        authentication: "10/minute"
        password_reset: "5/hour"
        registration: "3/hour"
        ai_inference: "50/minute"
      cors:
        allowed_origins:
          - "https://skillforge.ai"
          - "https://www.skillforge.ai"
          - "https://app.skillforge.ai"
        allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"]
        max_age: 86400
      csrf_protection:
        enabled: true
        token_length: 32
        secure_cookies: true
        samesite: "Strict"
    
    # Input Validation
    input_validation:
      sanitization:
        html_encoding: true
        sql_escaping: true
        javascript_escaping: true
        url_encoding: true
      validation_rules:
        email: "RFC 5322 compliant"
        phone: "E.164 format"
        urls: "whitelist approved domains"
        file_uploads:
          max_size: "10MB"
          allowed_types: ["pdf", "doc", "docx", "txt"]
          virus_scanning: true
      content_security_policy:
        default_src: "'self'"
        script_src: "'self' 'unsafe-inline' https://cdn.skillforge.ai"
        style_src: "'self' 'unsafe-inline' https://fonts.googleapis.com"
        img_src: "'self' data: https:"
        font_src: "'self' https://fonts.gstatic.com"
        connect_src: "'self' https://api.skillforge.ai"
        frame_ancestors: "'none'"
        base_uri: "'self'"
        form_action: "'self'"
    
    # Data Protection
    data_protection:
      gdpr_compliance:
        lawful_basis: "consent"
        data_minimization: true
        purpose_limitation: true
        accuracy_maintenance: true
        storage_limitation: true
        integrity_confidentiality: true
        accountability: true
      ccpa_compliance:
        consumer_rights: true
        opt_out_mechanisms: true
        data_deletion: true
        transparency_reporting: true
      retention_policies:
        user_data: "7 years after account deletion"
        logs: "90 days"
        backups: "30 days"
        analytics: "2 years anonymized"
        audit_logs: "7 years"
      anonymization:
        pii_removal: true
        k_anonymity: 5
        l_diversity: true
        t_closeness: true
    
    # Security Monitoring
    monitoring:
      logging:
        authentication_events: true
        authorization_failures: true
        data_access: true
        configuration_changes: true
        privilege_escalation: true
        suspicious_activities: true
      alerting:
        failed_logins: "5 attempts in 5 minutes"
        privilege_escalation: "immediate"
        data_exfiltration: "immediate"
        configuration_changes: "immediate"
        vulnerability_detection: "24 hours"
      incident_response:
        detection_time: "< 15 minutes"
        response_time: "< 30 minutes"
        containment_time: "< 2 hours"
        recovery_time: "< 24 hours"
        lessons_learned: "within 7 days"
    
    # Vulnerability Management
    vulnerability_management:
      scanning:
        frequency: "weekly"
        tools: ["OWASP ZAP", "Nessus", "Snyk"]
        coverage: "100% of infrastructure and applications"
      patching:
        critical: "within 24 hours"
        high: "within 7 days"
        medium: "within 30 days"
        low: "within 90 days"
      penetration_testing:
        frequency: "quarterly"
        scope: "full application and infrastructure"
        methodology: "OWASP Testing Guide"
        reporting: "within 2 weeks"
    
    # Access Control
    access_control:
      principle: "least privilege"
      rbac:
        roles:
          - "user"
          - "premium_user"
          - "admin"
          - "security_admin"
          - "system_admin"
        permissions:
          granular: true
          time_based: true
          location_based: true
      privileged_access:
        just_in_time: true
        approval_required: true
        session_recording: true
        regular_review: "monthly"
    
    # Business Continuity
    business_continuity:
      backup_strategy:
        frequency: "daily"
        retention: "30 days"
        testing: "monthly"
        encryption: "required"
        offsite_storage: true
      disaster_recovery:
        rto: "4 hours"  # Recovery Time Objective
        rpo: "1 hour"   # Recovery Point Objective
        testing: "quarterly"
        documentation: "updated monthly"
      incident_management:
        classification: "P0, P1, P2, P3"
        escalation_matrix: true
        communication_plan: true
        post_incident_review: true
    
    # Compliance
    compliance:
      frameworks:
        - "SOC 2 Type II"
        - "ISO 27001"
        - "GDPR"
        - "CCPA"
        - "OWASP Top 10"
      auditing:
        internal: "quarterly"
        external: "annually"
        penetration_testing: "quarterly"
        compliance_assessment: "annually"
      documentation:
        policies: "reviewed annually"
        procedures: "reviewed quarterly"
        training: "annually for all staff"
        awareness: "monthly security updates"
