apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: datadog-cluster-agent
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: datadog-cluster-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datadog-cluster-agent
        app.kubernetes.io/component: monitoring
      annotations:
        ad.datadoghq.com/cluster-agent.check_names: '["prometheus"]'
        ad.datadoghq.com/cluster-agent.init_configs: '[{}]'
        ad.datadoghq.com/cluster-agent.instances: '[{"prometheus_url": "http://prometheus-service:9090/metrics", "namespace": "skillforge_ai", "metrics": ["*"]}]'
    spec:
      serviceAccountName: datadog-cluster-agent
      containers:
      - name: cluster-agent
        image: gcr.io/datadoghq/cluster-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005
          name: agentport
          protocol: TCP
        - containerPort: 5000
          name: agentmetrics
          protocol: TCP
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: DD_APP_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: app-key
        - name: DD_CLUSTER_AGENT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: token
        - name: DD_CLUSTER_NAME
          value: "skillforge-ai-cluster"
        - name: DD_SITE
          value: "datadoghq.com"
        - name: DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME
          value: "datadog-cluster-agent"
        - name: DD_CLUSTER_AGENT_ENABLED
          value: "true"
        - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
          value: "true"
        - name: DD_EXTERNAL_METRICS_PROVIDER_PORT
          value: "8443"
        - name: DD_EXTERNAL_METRICS_PROVIDER_WPA_CONTROLLER
          value: "true"
        - name: DD_EXTERNAL_METRICS_PROVIDER_USE_DATADOGMETRIC_CRD
          value: "true"
        - name: DD_ADMISSION_CONTROLLER_ENABLED
          value: "true"
        - name: DD_ADMISSION_CONTROLLER_MUTATE_UNLABELLED
          value: "true"
        - name: DD_ADMISSION_CONTROLLER_SERVICE_NAME
          value: "datadog-admission-controller"
        - name: DD_CLUSTER_CHECKS_ENABLED
          value: "true"
        - name: DD_EXTRA_CONFIG_PROVIDERS
          value: "kube_endpoints kube_services"
        - name: DD_EXTRA_LISTENERS
          value: "kube_endpoints kube_services"
        - name: DD_LOG_LEVEL
          value: "INFO"
        - name: DD_LEADER_ELECTION
          value: "true"
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_CLUSTER_AGENT_COLLECT_KUBERNETES_TAGS
          value: "true"
        - name: DD_ORCHESTRATOR_EXPLORER_ENABLED
          value: "true"
        - name: DD_TAGS
          value: "env:production service:skillforge-ai"
        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: installinfo
          subPath: install_info
          mountPath: /etc/datadog-agent/install_info
          readOnly: true
      volumes:
      - name: installinfo
        configMap:
          name: datadog-installinfo
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-cluster-agent
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: datadog-cluster-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-cluster-agent
  labels:
    app.kubernetes.io/name: datadog-cluster-agent
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  - componentstatuses
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["quota.openshift.io"]
  resources:
  - clusterresourcequotas
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
- apiGroups: ["apiregistration.k8s.io"]
  resources:
  - apiservices
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames: ["datadog-leader-election", "datadog-custom-metrics"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["create"]
- nonResourceURLs:
  - "/version"
  - "/healthz"
  - "/metrics"
  verbs: ["get"]
- apiGroups: ["datadoghq.com"]
  resources:
  - datadogmetrics
  verbs: ["list", "create", "delete", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - replicasets
  - deployments
  - daemonsets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - serviceaccounts
  verbs: ["list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs: ["list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
  - mutatingwebhookconfigurations
  verbs: ["get", "list", "watch", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-cluster-agent
  labels:
    app.kubernetes.io/name: datadog-cluster-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-cluster-agent
subjects:
- kind: ServiceAccount
  name: datadog-cluster-agent
  namespace: skillforge-ai-monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: datadog-cluster-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: datadog-cluster-agent
  ports:
  - port: 5005
    name: agentport
    protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-installinfo
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: datadog-cluster-agent
data:
  install_info: |
    ---
    install_method:
      tool: kubernetes
      tool_version: kubectl
      installer_version: skillforge-ai-v1.0.0
