apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/component: monitoring
    spec:
      serviceAccountName: grafana
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-password
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,grafana-simple-json-datasource"
        - name: GF_SERVER_ROOT_URL
          value: "https://monitoring.skillforge.ai/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_USERS_AUTO_ASSIGN_ORG
          value: "true"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Viewer"
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: "smtp.gmail.com:587"
        - name: GF_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: smtp-user
        - name: GF_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: smtp-password
        - name: GF_SMTP_FROM_ADDRESS
          value: "alerts@skillforge.ai"
        - name: GF_SMTP_FROM_NAME
          value: "SkillForge AI Monitoring"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards-config
        configMap:
          name: grafana-dashboards-config
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    
    [grafana_net]
    url = https://grafana.net
    
    [log]
    mode = console
    level = info
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [server]
    protocol = http
    http_port = 3000
    domain = monitoring.skillforge.ai
    enforce_domain = false
    root_url = https://monitoring.skillforge.ai/grafana
    serve_from_sub_path = true
    
    [database]
    type = sqlite3
    path = grafana.db
    
    [session]
    provider = file
    
    [security]
    admin_user = admin
    admin_password = admin
    secret_key = SW2YcwTIb9zpOOhoPsMm
    disable_gravatar = false
    
    [snapshots]
    external_enabled = true
    external_snapshot_url = https://snapshots-origin.raintank.io
    external_snapshot_name = Publish to snapshot.raintank.io
    
    [dashboards]
    versions_to_keep = 20
    
    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    
    [auth.anonymous]
    enabled = false
    
    [auth.basic]
    enabled = true
    
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = alerts@skillforge.ai
    password = """your-smtp-password"""
    cert_file =
    key_file =
    skip_verify = false
    from_address = alerts@skillforge.ai
    from_name = SkillForge AI Monitoring
    ehlo_identity = skillforge.ai
    
    [emails]
    welcome_email_on_sign_up = false
    templates_pattern = emails/*.html
    
    [alerting]
    enabled = true
    execute_alerts = true
    error_or_timeout = alerting
    nodata_or_nullvalues = no_data
    concurrent_render_limit = 5
    
    [metrics]
    enabled = true
    interval_seconds = 10
    
    [metrics.graphite]
    address =
    prefix = prod.grafana.%(instance_name)s.
    
    [tracing.jaeger]
    address = jaeger:14268
    always_included_tag = tag1:value1
    sampler_type = const
    sampler_param = 1
    
    [external_image_storage]
    provider = s3
    
    [external_image_storage.s3]
    bucket = skillforge-ai-grafana-images
    region = us-west-2
    path = images

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: 15s
        queryTimeout: 60s
        httpMethod: POST
    - name: Datadog
      type: datadog
      access: proxy
      url: https://api.datadoghq.com
      jsonData:
        apiKey: ${DATADOG_API_KEY}
        appKey: ${DATADOG_APP_KEY}
      secureJsonData:
        apiKey: ${DATADOG_API_KEY}
        appKey: ${DATADOG_APP_KEY}
    - name: CloudWatch
      type: cloudwatch
      access: proxy
      jsonData:
        authType: default
        defaultRegion: us-west-2
        customMetricsNamespaces: SkillForge/AI,SkillForge/API,SkillForge/Jobs
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-service:3100
      jsonData:
        maxLines: 1000
        timeout: 60s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: skillforge-ai-monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'skillforge-ai'
      orgId: 1
      folder: 'SkillForge AI'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
