apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: skillforge-ai-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: skillforge-ai-platform
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: ai-services-service
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: ai-services
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: skillforge-ai-platform
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: ai-services

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: skillforge-ai-platform
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx

---
# Headless service for StatefulSet services (if needed)
apiVersion: v1
kind: Service
metadata:
  name: ai-services-headless
  namespace: skillforge-ai
  labels:
    app.kubernetes.io/name: ai-services
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: skillforge-ai-platform
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: ai-services
